language: node_js
node_js:
  - '8'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: s3
  access_key_id: $GATSBY_AWS_KEY
  secret_access_key: $GATSBY_AWS_SECRET_KEY
  bucket: "downthecode.com"
  skip_cleanup: true
  local_dir: public
